print("Hello, World!")
print("Welcome to Python programming.")
print("kevin")
print("wenas")
print("hola kevin")
print("hola kevin, como estas?")
print("hola kevin, como estas22222?")
print("hola kevin, como estas33333?")
print("hola kevin, como estas44444?")